"""
Define token types
"""
KEYWORD, IDENTIFIER, INTEGER, OPEN_BRACE, CLOSE_BRACE, OPEN_PAREN, CLOSE_PAREN, SEMICOLON = (
    'KEYWORD', 'IDENTIFIER', 'INTEGER', 'OPEN_BRACE', 'CLOSE_BRACE', 'OPEN_PAREN', 'CLOSE_PAREN', 'SEMICOLON'
)